/* eslint-disable prettier/prettier */
const TYPES = {
  ADD_ASOCIACIONESCOD: 'ADD_ASOCIACIONESCOD',
  ADD_ASOCIACIONESCOD_SUCCESS: 'ADD_ASOCIACIONESCOD_SUCCESS',
  ADD_ASOCIACIONESCOD_ERROR: 'ADD_ASOCIACIONESCOD_ERROR',
  OBTENER_ASOCIACIONESCOD: 'OBTENER_ASOCIACIONESCOD',
  OBTENER_ASOCIACIONESCOD_SUCCESS: 'OBTENER_ASOCIACIONESCOD_SUCCESS',
  OBTENER_ASOCIACIONESCOD_ERROR: 'OBTENER_ASOCIACIONESCOD_ERROR',
  OBTENER_ASOCIACIONESCOD_EDITAR: 'OBTENER_ASOCIACIONESCOD_EDITAR',
  EDITAR_ASOCIACIONESCOD: 'EDITAR_ASOCIACIONESCOD',
  EDITAR_ASOCIACIONESCOD_SUCCESS: 'EDITAR_ASOCIACIONESCOD_SUCCESS',
  EDITAR_ASOCIACIONESCOD_ERROR: 'EDITAR_ASOCIACIONESCOD_ERROR',
  DELETE_ASOCIACIONESCOD: 'DELETE_ASOCIACIONESCOD',
  DELETE_ASOCIACIONESCOD_SUCCESS: 'DELETE_ASOCIACIONESCOD_SUCCESS',
  DELETE_ASOCIACIONESCOD_ERROR: 'DELETE_ASOCIACIONESCOD_ERROR',
}
export default TYPES
