/* eslint-disable prettier/prettier */
const TYPES = {
  ADD_MUNICIPIO: 'ADD_MUNICIPIO',
  ADD_MUNICIPIO_SUCCESS: 'ADD_MUNICIPIO_SUCCESS',
  ADD_MUNICIPIO_ERROR: 'ADD_MUNICIPIO_ERROR',
  OBTENER_MUNICIPIO: 'OBTENER_MUNICIPIO',
  OBTENER_MUNICIPIO_SUCCESS: 'OBTENER_MUNICIPIO_SUCCESS',
  OBTENER_MUNICIPIO_ERROR: 'OBTENER_MUNICIPIO_ERROR',
  OBTENER_MUNICIPIO_EDITAR: 'OBTENER_MUNICIPIO_EDITAR',
  EDITAR_MUNICIPIO: 'EDITAR_MUNICIPIO',
  EDITAR_MUNICIPIO_SUCCESS: 'EDITAR_MUNICIPIO_SUCCESS',
  EDITAR_MUNICIPIO_ERROR: 'EDITAR_MUNICIPIO_ERROR',
  DELETE_MUNICIPIO: 'DELETE_MUNICIPIO',
  DELETE_MUNICIPIO_SUCCESS: 'DELETE_MUNICIPIO_SUCCESS',
  DELETE_MUNICIPIO_ERROR: 'DELETE_MUNICIPIO_ERROR',
}

export default TYPES
